package com.bitsfabrik.bitsstrings.generator.generators.resources.transformers

import com.bitsfabrik.bitsstrings.generator.generators.resources.formatting.key.AndroidKeyFormatter
import com.bitsfabrik.bitsstrings.generator.generators.resources.formatting.value.AndroidValueFormatter
import com.bitsfabrik.bitsstrings.generator.domain.BitsStringDefinition

/** Renders `res/values-<lang>/strings.xml`. */
internal class AndroidXmlTransformer : PerLanguageTransformer(
    AndroidValueFormatter,
    AndroidKeyFormatter
) {

    override fun fileHeader(language: String): String {
        return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<!--\tGenerated by Bitstring\t-->\n" +
                "<!--\tLanguage: $language\t\t\t-->\n" +
                "<resources>\n"
    }

    override fun fileFooter(): String {
        return "\n</resources>"
    }

    override fun sectionHeader(section: String): String {
        return "\n\t<!-- SECTION: $section --> \n"
    }

    override fun transformTranslation(key: String, value: String): String {
        return "\t<string name=\"${formatKey(key)}\">${formatValue(value)}</string>\n"
    }

    override fun transformPlural(
        definition: BitsStringDefinition.Plural,
        language: String,
    ): String = buildString {
        append("\t<plurals name=\"${formatKey(definition.key)}\">\n")

        definition.translations.forEach { (quantity, variation) ->
            append("\t\t<item quantity=\"$quantity\">${formatValue(variation[language].orEmpty())}</item>\n")
        }

        append("\t</plurals>\n")
    }
}