package com.bitsfabrik.bitsstrings.generator.generators.resources.transformers

import com.bitsfabrik.bitsstrings.generator.generators.resources.ResourceFileGenerationError
import com.bitsfabrik.bitsstrings.generator.generators.resources.formatting.key.IosKeyFormatter
import com.bitsfabrik.bitsstrings.generator.generators.resources.formatting.value.IosValueFormatter
import com.bitsfabrik.bitsstrings.generator.domain.BitsStringDefinition

/** Renders `<lang>.lproj/Localizable.strings`, the plural-less legacy apple format. */
internal class IosLegacyTransformer : PerLanguageTransformer(IosValueFormatter, IosKeyFormatter) {

    override fun fileHeader(language: String): String {
        return "/*\tGenerated by Bitstring \t*/\n" +
                "/*\tLanguage: $language \t\t\t*/\n"
    }

    override fun fileFooter(): String {
        return ""
    }

    override fun sectionHeader(section: String): String {
        return "\n/********** $section **********/\n"
    }

    override fun transformTranslation(key: String, value: String): String {
        return "\"${formatKey(key)}\" = \"${formatValue(value)}\";\n"
    }

    override fun transformPlural(
        definition: BitsStringDefinition.Plural,
        language: String,
    ): String = throw ResourceFileGenerationError(
        "Plurals are not permitted with legacy strings generation"
    )
}