package com.bitsfabrik.bitsstrings.generator.generators.resources.transformers

import com.bitsfabrik.bitsstrings.generator.testing.bitsStringFile
import com.bitsfabrik.bitsstrings.generator.testing.plural
import com.bitsfabrik.bitsstrings.generator.testing.section
import com.bitsfabrik.bitsstrings.generator.testing.singular
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFalse

class AndroidXmlTransformerTest {

    private val transformer = AndroidXmlTransformer()

    @Test
    fun rendersOneCompleteDocumentPerLanguage() {
        val file = bitsStringFile(
            section(
                "General",
                singular("general_label_ok", "de" to "OK", "en" to "Yes"),
                plural(
                    "general_message_count",
                    "one" to mapOf("de" to "Eine Nachricht", "en" to "One message"),
                    "other" to mapOf("de" to "%d Nachrichten", "en" to "%d messages"),
                ),
            ),
            section(
                "Login",
                singular("login_label_resetMail", "de" to "Mail an %@", "en" to "Mail to %@"),
            ),
        )

        val expectedGerman =
            "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                    "<!--\tGenerated by Bitstring\t-->\n" +
                    "<!--\tLanguage: de\t\t\t-->\n" +
                    "<resources>\n" +
                    "\n" +
                    "\t<!-- SECTION: General --> \n" +
                    "\t<string name=\"general_label_ok\">OK</string>\n" +
                    "\t<plurals name=\"general_message_count\">\n" +
                    "\t\t<item quantity=\"one\">Eine Nachricht</item>\n" +
                    "\t\t<item quantity=\"other\">%1\$d Nachrichten</item>\n" +
                    "\t</plurals>\n" +
                    "\n" +
                    "\t<!-- SECTION: Login --> \n" +
                    "\t<string name=\"login_label_reset_mail\">Mail an %1\$s</string>\n" +
                    "\n</resources>"

        assertEquals(listOf("de", "en"), transformer.processBitString(file).keys.toList())
        assertEquals(expectedGerman, transformer.processBitString(file)["de"])
    }

    @Test
    fun aMissingTranslationBecomesAnEmptyStringElement() {
        val file = bitsStringFile(
            section("General", singular("general_label_ok", "de" to "OK", "en" to "Yes")),
            section("Login", singular("login_label_only_german", "de" to "Nur deutsch")),
        )

        val english = transformer.processBitString(file).getValue("en")

        assertContains(english, "\t<string name=\"login_label_only_german\"></string>\n")
    }

    @Test
    fun aMissingPluralQuantityBecomesAnEmptyItem() {
        val file = bitsStringFile(
            section(
                "General",
                plural(
                    "general_message_count",
                    "one" to mapOf("de" to "Eine", "en" to "One"),
                    "other" to mapOf("de" to "Viele"),
                ),
            ),
        )

        val english = transformer.processBitString(file).getValue("en")

        assertContains(english, "\t\t<item quantity=\"one\">One</item>\n")
        assertContains(english, "\t\t<item quantity=\"other\"></item>\n")
    }

    @Test
    fun escapesXmlSpecialCharactersButKeepsAllowedHtmlTags() {
        val file = bitsStringFile(
            section(
                "General",
                singular(
                    "general_label_html",
                    "de" to "A & B <b>bold</b> <a href=\"mailto\">mail</a> 'quoted' <unknown>",
                ),
            ),
        )

        val german = transformer.processBitString(file).getValue("de")

        assertContains(
            german,
            "<string name=\"general_label_html\">" +
                    "A &amp; B <b>bold</b> <a href=\"mailto\">mail</a> \\'quoted\\' &lt;unknown&gt;" +
                    "</string>"
        )
    }

    @Test
    fun numbersPlaceholdersPerTranslationRatherThanPerFile() {
        val file = bitsStringFile(
            section(
                "General",
                singular("general_label_first", "de" to "%s and %d"),
                singular("general_label_second", "de" to "%@ again"),
            ),
        )

        val german = transformer.processBitString(file).getValue("de")

        assertContains(german, "<string name=\"general_label_first\">%1\$s and %2\$d</string>")
        assertContains(german, "<string name=\"general_label_second\">%1\$s again</string>")
    }

    @Test
    fun rendersAnEmptyResourcesDocumentForAFileWithoutStrings() {
        val file = bitsStringFile(section("General"))

        // no language means no file — there is nothing to translate
        assertEquals(emptyMap(), transformer.processBitString(file))
    }

    @Test
    fun doesNotEmitPluralsMarkupForSingularsOnly() {
        val file = bitsStringFile(section("General", singular("general_label_ok", "de" to "OK")))

        assertFalse(transformer.processBitString(file).getValue("de").contains("<plurals"))
    }
}
