package com.bitsfabrik.bitsstrings.generator.generators.resources.transformers

import com.bitsfabrik.bitsstrings.generator.generators.resources.ResourceFileGenerationError
import com.bitsfabrik.bitsstrings.generator.testing.bitsStringFile
import com.bitsfabrik.bitsstrings.generator.testing.plural
import com.bitsfabrik.bitsstrings.generator.testing.section
import com.bitsfabrik.bitsstrings.generator.testing.singular
import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

class IosLegacyTransformerTest {

    private val transformer = IosLegacyTransformer()

    @Test
    fun rendersOneCompleteStringsFilePerLanguage() {
        val file = bitsStringFile(
            section(
                "General",
                singular("general_label_ok", "de" to "OK", "en" to "Yes"),
            ),
            section(
                "Login",
                singular("login_label_resetMail", "de" to "Mail an %s"),
            ),
        )

        val expectedGerman =
            "/*\tGenerated by Bitstring \t*/\n" +
                    "/*\tLanguage: de \t\t\t*/\n" +
                    "\n/********** General **********/\n" +
                    "\"general.label.ok\" = \"OK\";\n" +
                    "\n/********** Login **********/\n" +
                    "\"login.label.resetMail\" = \"Mail an %1\$@\";\n"

        assertEquals(listOf("de", "en"), transformer.processBitString(file).keys.toList())
        assertEquals(expectedGerman, transformer.processBitString(file)["de"])
    }

    @Test
    fun mapsKeysToTheDottedAppleConvention() {
        val file = bitsStringFile(
            section("General", singular("login_label_PasswordReset", "de" to "Reset")),
        )

        assertContains(
            transformer.processBitString(file).getValue("de"),
            "\"login.label.PasswordReset\" = \"Reset\";"
        )
    }

    @Test
    fun escapesNestedQuotes() {
        val file = bitsStringFile(
            section("General", singular("general_label_quoted", "de" to "sag \"hallo\" bitte")),
        )

        assertContains(
            transformer.processBitString(file).getValue("de"),
            "\"general.label.quoted\" = \"sag \\\"hallo\\\" bitte\";"
        )
    }

    @Test
    fun aMissingTranslationBecomesAnEmptyValue() {
        val file = bitsStringFile(
            section(
                "General",
                singular("general_label_ok", "de" to "OK", "en" to "Yes"),
                singular("general_label_onlyGerman", "de" to "Nur deutsch"),
            ),
        )

        assertContains(
            transformer.processBitString(file).getValue("en"),
            "\"general.label.onlyGerman\" = \"\";"
        )
    }

    @Test
    fun rejectsPluralsBecauseTheLegacyFormatCannotExpressThem() {
        val file = bitsStringFile(
            section(
                "General",
                plural("general_message_count", "one" to mapOf("de" to "Eine")),
            ),
        )

        val error = assertFailsWith<ResourceFileGenerationError> {
            transformer.processBitString(file)
        }

        assertEquals("Plurals are not permitted with legacy strings generation", error.message)
    }
}
